services:
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - net1
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  php:
    container_name: ${APP_NAME}-php
    build:
      dockerfile: ./docker/php.dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/var/www/
    networks:
      - net1
    entrypoint: bash -c "echo \"ready\" && sleep 86400"

networks:
  net1:
    driver: bridge
